version: '3.9'
services:
    app: &app_service
        build:
            context: .
            dockerfile: swoole.dockerfile
            target: dev
        volumes:
            - ./:/app
        environment:
            DATABASE_URL: "postgresql://db_user:fake_password@db:5432/picpay?serverVersion=16&charset=utf8"
            APP_ENV: dev
            APP_RUNTIME: "Runtime\\Swoole\\Runtime"
            SWOOLE_HOST: "0.0.0.0"
            SWOOLE_PORT: "8000"
        depends_on:
            - db
    fpm:
        build:
            context: .
            dockerfile: fpm.dockerfile
            target: dev
        volumes:
            - ./:/app
            - ./fpm.ini:/usr/local/etc/php-fpm.d/zz-app.conf
        environment:
            DATABASE_URL: "postgresql://db_user:fake_password@db:5432/picpay?serverVersion=16&charset=utf8"
            APP_ENV: dev
    web:
        image: nginx:1.25-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8123:80"
            - "8124:8080"
        depends_on:
            - app
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: picpay
            POSTGRES_PASSWORD: fake_password
            POSTGRES_USER: db_user
        volumes:
            - database_data:/var/lib/postgresql/data:rw
    migrations:
        <<: *app_service
        command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]
        restart: on-failure
volumes:
    database_data:
